spring.application.name=Sport E-Commerce

spring.datasource.url=jdbc:postgresql://ep-silent-bar-b44aon53-pooler.c-6.us-east-2.aws.neon.tech:5432/sport_ecommerce?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lP6pb8sWLJmr
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== API Giao H\u00E0ng Nhanh (GHN) =====
shipping.cancel-order=true
shipping.ghn.base-url=https://dev-online-gateway.ghn.vn/shiip/public-api
shipping.ghn.token=ded4e2c6-b4c1-11f1-a973-aee5264794df
shipping.ghn.shop-id=222414
shipping.ghn.from-district-id=1461

# ===== API Giao H\u00E0ng Ti\u1EBFt Ki\u1EC7m (GHTK) =====
shipping.ghtk.base-url=https://services.giaohangtietkiem.vn
shipping.ghtk.token=538a2bOSZcST32PQZhTENIBRXbDXCFtJez8xiiZ
shipping.ghtk.pick-province=H\u1ED3 Ch\u00ED Minh
shipping.ghtk.pick-district=Qu\u1EADn G\u00F2 V\u1EA5p
shipping.ghtk.pick-ward=Ph\u01B0\u1EDDng 1
shipping.ghtk.pick-address=12 Nguy\u1EC5n V\u0103n B\u1EA3o
shipping.ghtk.pick-tel=0123456789

# ===== JWT =====
app.jwt.secret=${JWT_SECRET_KEY:day_la_khoa_bi_mat_jwt_dai_it_nhat_256_bit_hoac_32_ky_tu_tro_len_123456}
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

# ===== Redis (OTP cache) =====
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# ===== OTP =====
app.otp.length=6
app.otp.ttl-seconds=120
app.otp.max-attempts=5
app.otp.resend-cooldown-seconds=60

# ===== Mail =====
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=${MAIL_FROM:no-reply@sportecommerce.com}
app.mail.from-name=Sport E-Commerce

# ===== VNPay =====
vnpay.tmn-code=6HL2G72A
vnpay.hash-secret=ZYARDHRCTAYKLOKCSERWGSCZOONKVPPX
vnpay.pay-url=${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:5173/payment-result}

